package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEPARTMENT.
 */
public class Department {

    private Long id;
    private String parentID;
    private String name;
    private String code;
    private String abbreviation;
    private Integer isCompany;

    public Department() {
    }

    public Department(Long id) {
        this.id = id;
    }

    public Department(Long id, String parentID, String name, String code, String abbreviation, Integer isCompany) {
        this.id = id;
        this.parentID = parentID;
        this.name = name;
        this.code = code;
        this.abbreviation = abbreviation;
        this.isCompany = isCompany;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getParentID() {
        return parentID;
    }

    public void setParentID(String parentID) {
        this.parentID = parentID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public Integer getIsCompany() {
        return isCompany;
    }

    public void setIsCompany(Integer isCompany) {
        this.isCompany = isCompany;
    }

}
