package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STAFF.
 */
public class Staff {

    private Long id;
    private String name;
    private String code;
    private String departmentID;
    private String departmentCode;
    private String mobile;
    private String telephone;
    private String email;
    private Integer gender;
    private Integer isMainDepartment;

    public Staff() {
    }

    public Staff(Long id) {
        this.id = id;
    }

    public Staff(Long id, String name, String code, String departmentID, String departmentCode, String mobile, String telephone, String email, Integer gender, Integer isMainDepartment) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.departmentID = departmentID;
        this.departmentCode = departmentCode;
        this.mobile = mobile;
        this.telephone = telephone;
        this.email = email;
        this.gender = gender;
        this.isMainDepartment = isMainDepartment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDepartmentID() {
        return departmentID;
    }

    public void setDepartmentID(String departmentID) {
        this.departmentID = departmentID;
    }

    public String getDepartmentCode() {
        return departmentCode;
    }

    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Integer getIsMainDepartment() {
        return isMainDepartment;
    }

    public void setIsMainDepartment(Integer isMainDepartment) {
        this.isMainDepartment = isMainDepartment;
    }

}
